-- AlterTable
ALTER TABLE `Room` MODIFY `operationalStatus` ENUM('ACTIVE', 'CLEANING', 'MAINTENANCE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Stay` ADD COLUMN `vehicleType` ENUM('MOTORCYCLE', 'CAR', 'VAN', 'TRICYCLE', 'OTHER_VEHICLE') NULL;

-- AlterTable
ALTER TABLE `Booking` ADD COLUMN `vehicleType` ENUM('MOTORCYCLE', 'CAR', 'VAN', 'TRICYCLE', 'OTHER_VEHICLE') NULL;
